### ISSUE TITLE
Email piping replacement

### ISSUE THREAD

**Issue by bilogic** [ingenerator/mailhook#6]
Hi!

I was hoping to use this to pipe emails over the network. Would you have any idea on how to handle network failures? i.e. ensure we don't lose any emails because the network was down temporarily.

**Comment by acoulton** [comment]
Hi,

I wouldn't recommend using this for that purpose. Mailhook is really just designed for capturing emails with roughly-known content for assertions during integration / blackbox testing, there are no guarantees about its ability to capture, parse or forward arbitrary mails in a production context. Also we're actually no longer using the postfix element of this package.

If you're using postfix there's a wide range of forwarders directly built in to postfix or available as plugins, I'd take a look at those.

Cheers

**Comment by bilogic** [comment]
ok thanks, but I hardly come across any for postfix, do you happen to know any?

**Comment by acoulton** [comment]
Afraid not - we developed a basic understanding of postfix as a relay for testing SMTP from PHP, but we don't use it any more.
